version: '3'
services:
  node:
    container_name: project_node
    image: node:latest
    working_dir: /home/node/app
    command: 
      - /bin/sh
      - '-c'
      - 'npm install && npm start'
    ports:
      - '3000:3000'
    volumes:
      - './src:/home/node/app'
    links: 
      - mongo
    depends_on:
      - mongo
    networks:
      - my-network
  mongo: 
    container_name: project_mongo
    image: 'mongo:latest'
    ports: 
      - '27017:27017'
networks:
  my-network: 
    driver: bridge
